### ISSUE TITLE
La recherche morphologique bugue sur le terme ἀρχισυνάγωγον (Ac 18, 8.17)

### ISSUE THREAD

**Issue by cibvia** [a2ohm/theke#12]

**Comment by a2ohm** [comment]
Il semble que ce soit un problème lié à la source.
Lorsque la source est 2TGreek, l'outil de recherche ne donne aucun résultat.
Lorsque la source est MorphoGNT, il en donne.

À explorer ...

**Comment by cibvia** [comment]
Bug similaire sur Ἀκύλας en Ac 18, 2 et 18.
Ici, il semble que la virgule qui suit le nom soit responsable du bug.
![image](https://user-images.githubusercontent.com/15103269/143254428-b224937c-0faa-4738-a2cb-7d75a49c7997.png)

**Comment by a2ohm** [comment]
Le problème vient du code strong (car la recherche est faite à partir du code strong).
Dans le module MorphGNT, le code Strong est toujours sur 4 chiffres, des zéros étant ajoutés si nécessaire.
Dans le module 2TGreek, ce n'est pas le cas.

ex. Ακύλας --> G**0**207 (MorphoGNT) / G207 (2TGreek)

Comme le dictionnaire personnel associe chaque définition à un code Strong, j'ai du choisir une convention, et j'ai choisi celle de MorphoGNT. (cf. [5237df6](https://github.com/a2ohm/theke/commit/5237df6016a96836290a8ea42e73b7851e9fe5ea)

Or, pour le moment, la recherche est faite en utilisant cette convention.
Lorsque qu'un ou plusieurs zéros ont dû être ajouté, c'est normal qu'aucune occurrence ne soit trouvé dans 2TGreek.

**Comment by cibvia** [comment]
Ok, alors la virgule ne doit y être pour rien.
Cependant, elle apparaît dans la fenêtre morphologique, ce qui fait un peu tâche.

**Comment by a2ohm** [comment]
Problème à moitié résolu car si la recherche d’occurrence fonctionne maintenant avec le module 2TGreek, elle retourne malheureusement trop de résultats ...

Ainsi, une recherche sur Ακύλας (G**207**) retournera aussi les occurrences de ἑσπέρα (G**207**3),  ἔσχατος (G**207**8), etc.

Ce problème semble interne à la librairie Sword et à la façon dont les codes Strong sont formatés dans le module 2TGreek.
