### ISSUE TITLE
Conservation des sources

### ISSUE THREAD

**Issue by a2ohm** [a2ohm/theke#7]
_Garder les mêmes sources lorsque l'on passe d'un chapitre à l'autre d'un livre depuis la gotobar._

> En tapant Acts 27 dans la barre de recherche, on perd le double affichage, seul le grec demeure. On peut contourner le pb en cliquant sur le chapitre 27 dans la barre de gauche, mais ça serait intéressant de garder systématiquement les doubles affichages même en changeant de livre. Et pourquoi pas, même en changeant de langue (grec NT -> hébreu AT ?).

**Comment by cibvia** [comment]
Remarque : quand on fait une recherche morphologique à partir d'un mot grec ou hébreu, le double affichage est bien conservé !

**Comment by cibvia** [comment]
Question annexe du coup : y a-t-il un module sword pour le texte de la LXX, et encore mieux, pour une version unifiée de toute la bible en grec, ce qui permettrait d'avoir les résultats morphologiques sur toute la Bible et pas seulement un seul testament à la fois… ?

**Comment by a2ohm** [comment]
Il y a le module 2TGreek (dépôt Xiphos), mais la morphologie n'est pas encore compatible avec Theke ...
